name: Go

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          go test ./collections/...
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ runner.arch }}

  release:
    types:
      - app
    branches:
      - master
